// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgrjpyxoymhwillhmjjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncmpweXhveW1od2lsbGhtampoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzE3NzYsImV4cCI6MjA2NzU0Nzc3Nn0.gh9zTaO3toOelvJ8GN8C2Z-qNcscF6IG4q6iD0MLBY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});